export const REQ_LOGIN = 'REQ_LOGIN';
export const REQ_LOGIN_SUCCESS = 'REQ_LOGIN_SUCCESS';
export const REQ_LOGIN_FAILED = 'REQ_LOGIN_FAILED';
export const GET_COMMIT_LIST = 'GET_COMMIT_LIST';
export const GET_COMMIT_LIST_SUCCESS = 'GET_COMMIT_LIST_SUCCESS';
export const GET_COMMIT_LIST_FAILED = 'GET_COMMIT_LIST_FAILED';
